module.exports = {
    verbose: true,
    automock: false,
    collectCoverage: true,
    transform: {
        '^.+\\.jsx?$': 'babel-jest',
        '^.+\\.tsx?$': 'ts-jest',
        '.(ts|tsx)': './node_modules/ts-jest/preprocessor.js',
    },
    testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$',
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
    setupTestFrameworkScriptFile: './node_modules/jest-enzyme/lib/index.js',
    collectCoverageFrom: [
        'src/**/*.{js,jsx}',
        'src/**/*.{ts,tsx}',
        'src/**/**/*.{ts,tsx}',
        'src/**/**/*.{js,jsx}',
        '!src/**/*.stories.{js,jsx,ts,tsx}',
        '!src/**/validationSchema.ts',
        '!src/**/appStore/index.ts',
        '!src/index.tsx',
        '!src/components/app/index.tsx',
        '!src/utils/scrollToTop.tsx',
        '!src/config/**',
        '!src/registerServiceWorker.ts'
    ],
    testPathIgnorePatterns: ['/node_modules/'],
    coverageThreshold: {
        global: {
            branches: 0,
            functions: 0,
            lines: 0,
            statements: 0,
        },
    },
    notify: true,
    setupFiles: ['./jestSetup.js'],
    moduleNameMapper: {
        '^root(.*)$': '<rootDir>/src$1',
        '^actions(.*)$': '<rootDir>/src/actions$1',
        '^atoms(.*)$': '<rootDir>/src/components/atoms$1',
        '^components(.*)$': '<rootDir>/src/components$1',
        '^config(.*)$': '<rootDir>/src/config$1',
        '^containers(.*)$': '<rootDir>/src/containers$1',
        '^controllers(.*)$': '<rootDir>/src/controllers$1',
        '^helpers(.*)$': '<rootDir>/src/helpers$1',
        '^middleware(.*)$': '<rootDir>/src/middleware$1',
        '^molecules(.*)$': '<rootDir>/src/components/molecules$1',
        '^organisms(.*)$': '<rootDir>/src/components/organisms$1',
        '^pages(.*)$': '<rootDir>/src/components/pages$1',
        '^stores(.*)$': '<rootDir>/src/stores$1',
        '^types(.*)$': '<rootDir>/src/types$1',
        '^utils(.*)$': '<rootDir>/src/utils$1',
        '\\.(css|less)$': 'identity-obj-proxy',
        '^!babel-loader!svg-react-loader.*$': '<rootDir>/jest/svgImportMock.js',
        '^!babel-loader!url-loader.*$': '<rootDir>/jest/imgImportMock.js',
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/assetsTransformer.js',
        '\\.(css|less)$': '<rootDir>/assetsTransformer.js',
    },
    globals: {
        'ts-jest': {
            babelConfig: {
                plugins: ['syntax-dynamic-import', 'dynamic-import-node'],
            },
        },
    },
};